version: '3.8'

# Déclaration du réseau commun pour tous les services
networks:
  hadoop_network:
    driver: bridge

services:
  # Service du NameNode Hadoop
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    restart: always
    ports:
      - "50070:50070"  # Port de l'interface Web du NameNode
    volumes:
      - namenode:/hadoop/dfs/name  # Volume pour la persistance des données du NameNode
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env  # Fichier d'environnement pour les variables personnalisées
    networks:
      - hadoop_network

  # Service du DataNode Hadoop
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    restart: always
    ports:
      - "50075:50075"  # Port de l'interface Web du DataNode
    volumes:
      - datanode:/hadoop/dfs/data  # Volume pour la persistance des données du DataNode
    environment:
      SERVICE_PRECONDITION: "namenode:50070"  # Assure que le NameNode est actif avant le lancement du DataNode
    env_file:
      - ./hadoop-hive.env
    networks:
      - hadoop_network
    depends_on:
      - namenode

  # Serveur Hive pour exécuter les requêtes SQL
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    restart: always
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"  # Vérifie la disponibilité du metastore avant le démarrage
    ports:
      - "10000:10000"  # Port JDBC de HiveServer2 pour les connexions SQL
    env_file:
      - ./hadoop-hive.env
    networks:
      - hadoop_network
    depends_on:
      - hive-metastore

  # Metastore de Hive pour stocker les métadonnées
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    restart: always
    command: /opt/hive/bin/hive --service metastore  # Lance le service de métastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"  # Port pour accéder au métastore
    env_file:
      - ./hadoop-hive.env
    networks:
      - hadoop_network
    depends_on:
      - namenode
      - datanode
      - hive-metastore-postgresql

  # Base de données PostgreSQL pour le métastore de Hive
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    restart: always
    ports:
      - "5432:5432"  # Port par défaut de PostgreSQL
    networks:
      - hadoop_network

  # Serveur Presto pour les requêtes rapides et interactives
  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    container_name: presto-coordinator
    restart: always
    ports:
      - "8080:8080"  # Port pour l'interface Web et les requêtes de Presto
    networks:
      - hadoop_network

  # Service MongoDB pour le stockage NoSQL
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"  # Port par défaut pour MongoDB
    volumes:
      - mongo_data:/data/db  # Volume pour la persistance des données MongoDB
    networks:
      - hadoop_network

  # Serveur Oracle NoSQL
  oracle-nosql:
    image: ghcr.io/oracle/nosql:latest-ce
    container_name: oracle-nosql
    restart: always
    environment:
      - KVSTORE=kvstore
      - HOSTNAME=oracle-nosql
      - HA_HOSTNAME=oracle-nosql
    ports:
      - "8081:8080"
    volumes:
      - oracle_nosql_data:/data
    networks:
      - hadoop_network

# Déclaration des volumes pour la persistance des données
volumes:
  namenode:
  datanode:
  mongo_data:
  oracle_nosql_data:
